name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:

  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
      - name: Personal metrics
        uses: trinib/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: 📈GitHub action updated profile metrics📈
          base: "header, activity, community, repositories"
          plugin_fortune: yes
          plugin_introduction: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, comment, push, star
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 800
          plugin_people_size: 28
